# Generated by Django 3.1.3 on 2020-11-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
